# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"suma_de_arreglo": "01_preprocessing.ipynb"}

modules = ["preprocessing.py"]

doc_url = "https://alceballosa.github.io/dengue-forecasting/"

git_url = "https://github.com/alceballosa/dengue-forecasting/tree/master/"

def custom_doc_links(name): return None
