# AUTOGENERATED! DO NOT EDIT! File to edit: 01_preprocessing.ipynb (unless otherwise specified).

__all__ = ['suma_de_arreglo']

# Cell

def suma_de_arreglo(arreglo):
    return np.sum(arreglo)

print(suma_de_arreglo(np.array([10,20])))